version: 2
updates:
  - package-ecosystem: "bun"
    directory: "/www"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bun"
    directory: "/docs"
    schedule:
      interval: "weekly"
