services:
  www:
    build: .
    volumes:
      - type: bind
        source: .
        target: /proj/src
      # do not mount .next
      - /proj/src/.next
    ports:
      - '3000:3000'
    develop:
      watch:
        - path: .
          action: sync
          target: /proj/src
    environment:
      - BUILD_MODE=$BUILD_MODE
