import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="mx-auto flex min-h-screen max-w-7xl flex-col justify-between transition">
        <div className="mt-22">{children}</div>

        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
