name: Create Release From Tag

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    name: Create Release From Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Release
        run: |
          tag=$(git describe --tags --exact-match)
          gh release create "$tag" --generate-notes
