name: Prettier
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: www

      - name: "Package Script: prettier:check"
        run: bun run prettier:check
        working-directory: www
