name: Prettier
on: push

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --force

      - name: 'Package Script: prettier:check'
        run: npm run prettier:check
